/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TweetsRouteImport } from './routes/tweets'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as MediaRouteImport } from './routes/media'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'

const TweetsRoute = TweetsRouteImport.update({
  id: '/tweets',
  path: '/tweets',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/media': typeof MediaRoute
  '/posts': typeof PostsRouteWithChildren
  '/tweets': typeof TweetsRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/media': typeof MediaRoute
  '/posts': typeof PostsRouteWithChildren
  '/tweets': typeof TweetsRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/media': typeof MediaRoute
  '/posts': typeof PostsRouteWithChildren
  '/tweets': typeof TweetsRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/media' | '/posts' | '/tweets' | '/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/media' | '/posts' | '/tweets' | '/posts/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/media'
    | '/posts'
    | '/tweets'
    | '/posts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MediaRoute: typeof MediaRoute
  PostsRoute: typeof PostsRouteWithChildren
  TweetsRoute: typeof TweetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tweets': {
      id: '/tweets'
      path: '/tweets'
      fullPath: '/tweets'
      preLoaderRoute: typeof TweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
  }
}

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MediaRoute: MediaRoute,
  PostsRoute: PostsRouteWithChildren,
  TweetsRoute: TweetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
